# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1183, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(2, 0, -1, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.showpanel = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showpanel.sizePolicy().hasHeightForWidth())
        self.showpanel.setSizePolicy(sizePolicy)
        self.showpanel.setMinimumSize(QtCore.QSize(300, 0))
        self.showpanel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.showpanel.setObjectName("showpanel")
        self.verticalLayout_2.addWidget(self.showpanel)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 0))
        self.label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.objectname = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectname.sizePolicy().hasHeightForWidth())
        self.objectname.setSizePolicy(sizePolicy)
        self.objectname.setMinimumSize(QtCore.QSize(300, 0))
        self.objectname.setMaximumSize(QtCore.QSize(300, 16777215))
        self.objectname.setObjectName("objectname")
        self.verticalLayout_2.addWidget(self.objectname)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.picture = QtWidgets.QGridLayout()
        self.picture.setSpacing(0)
        self.picture.setObjectName("picture")
        self.horizontalLayout_3.addLayout(self.picture)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1183, 18))
        self.menubar.setObjectName("menubar")
        self.menudasdas = QtWidgets.QMenu(self.menubar)
        self.menudasdas.setObjectName("menudasdas")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        self.menu_7 = QtWidgets.QMenu(self.menu_2)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menu_7)
        self.menu_8.setObjectName("menu_8")
        self.menu_9 = QtWidgets.QMenu(self.menu_7)
        self.menu_9.setObjectName("menu_9")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionNDVI = QtWidgets.QAction(MainWindow)
        self.actionNDVI.setObjectName("actionNDVI")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.actionNDVI_2 = QtWidgets.QAction(MainWindow)
        self.actionNDVI_2.setObjectName("actionNDVI_2")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.addfile = QtWidgets.QAction(MainWindow)
        self.addfile.setObjectName("addfile")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.actiontxt = QtWidgets.QAction(MainWindow)
        self.actiontxt.setObjectName("actiontxt")
        self.actionshp = QtWidgets.QAction(MainWindow)
        self.actionshp.setObjectName("actionshp")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.actiondx = QtWidgets.QAction(MainWindow)
        self.actiondx.setObjectName("actiondx")
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actiona_2 = QtWidgets.QAction(MainWindow)
        self.actiona_2.setObjectName("actiona_2")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_17 = QtWidgets.QAction(MainWindow)
        self.action_17.setObjectName("action_17")
        self.menudasdas.addSeparator()
        self.menudasdas.addAction(self.addfile)
        self.menudasdas.addAction(self.action_7)
        self.menudasdas.addSeparator()
        self.menudasdas.addAction(self.action_13)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.actionNDVI)
        self.menu.addAction(self.action_3)
        self.menu_3.addAction(self.action_17)
        self.menu_3.addAction(self.action_14)
        self.menu_8.addAction(self.actiontxt)
        self.menu_9.addAction(self.action_9)
        self.menu_9.addAction(self.action_8)
        self.menu_7.addAction(self.menu_9.menuAction())
        self.menu_7.addAction(self.actionshp)
        self.menu_7.addAction(self.actionNDVI_2)
        self.menu_7.addAction(self.menu_8.menuAction())
        self.menu_7.addSeparator()
        self.menu_2.addAction(self.menu_7.menuAction())
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_12)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_15)
        self.menubar.addAction(self.menudasdas.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showpanel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">信息在此显示</p></body></html>"))
        self.label.setText(_translate("MainWindow", "标签名"))
        self.menudasdas.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "预处理"))
        self.menu_2.setTitle(_translate("MainWindow", "采样"))
        self.menu_3.setTitle(_translate("MainWindow", "深度学习样本"))
        self.menu_7.setTitle(_translate("MainWindow", "图像分类样本"))
        self.menu_8.setTitle(_translate("MainWindow", "自动采样"))
        self.menu_9.setTitle(_translate("MainWindow", "全要素分类"))
        self.action_2.setText(_translate("MainWindow", "锐化"))
        self.actionNDVI.setText(_translate("MainWindow", "NDVI"))
        self.action_3.setText(_translate("MainWindow", "图像变化"))
        self.action_5.setText(_translate("MainWindow", "影像剪裁"))
        self.action_8.setText(_translate("MainWindow", "全栅格自动采集"))
        self.actionNDVI_2.setText(_translate("MainWindow", "NDVI采样"))
        self.action_9.setText(_translate("MainWindow", "手动跟踪数字化"))
        self.action_11.setText(_translate("MainWindow", "开始采样"))
        self.action_12.setText(_translate("MainWindow", "撤销标记"))
        self.action.setText(_translate("MainWindow", "尺寸"))
        self.addfile.setText(_translate("MainWindow", "打开"))
        self.action_7.setText(_translate("MainWindow", "样本库"))
        self.action_4.setText(_translate("MainWindow", "多边形"))
        self.action_10.setText(_translate("MainWindow", "矩形"))
        self.actiontxt.setText(_translate("MainWindow", "txt文件"))
        self.actionshp.setText(_translate("MainWindow", "矢量掩膜采样"))
        self.action_6.setText(_translate("MainWindow", "移动窗口"))
        self.action_13.setText(_translate("MainWindow", "关闭"))
        self.actiondx.setText(_translate("MainWindow", "dx"))
        self.actiona.setText(_translate("MainWindow", "a"))
        self.actiona_2.setText(_translate("MainWindow", "a"))
        self.action_14.setText(_translate("MainWindow", "目标检测"))
        self.action_15.setText(_translate("MainWindow", "样本测试"))
        self.action_17.setText(_translate("MainWindow", "样本标注"))
